services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - docker-network
        ports:
            - 9001:9000
        volumes:
            - app-data:/var/www/html
            - node_modules:/var/www/html/node_modules
        env_file:
           - .env
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

volumes:
    app-data: {}
    node_modules: {}

networks:
    docker-network:
        driver: bridge
