services:
    app:
        build:
            dockerfile: Dockerfile
        restart: unless-stopped
        networks:
            - docker-network
        ports:
            - 9001:9000
        volumes:
            - .:/var/www/html
            - node_modules:/var/www/html/node_modules

#Remove this service for production use
    caddy:
        image: caddy:latest
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/html
            - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
            - docker-network
        depends_on:
            - app

volumes:
    node_modules: {}

networks:
    docker-network:
        driver: bridge
