services:
    cervejaria-backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        container_name: cervejaria-backend
        networks:
            - proxy-network
        ports:
            - 127.0.0.1:9000:9000
        volumes:
            - .:/var/www/html
        env_file:
           - .env
        environment:
            - DB_HOST=${DB_HOST}
            - DB_PORT=${DB_PORT}
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

networks:
    proxy-network:
        external: true
