name: Deploy to Development (VPS)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 75.119.133.70 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        ssh root@75.119.133.70 << 'EOF'
          cd /var/www/cervejaria-backend
          git pull origin dev
          docker-compose down
          docker-compose up -d --build
	  docker restart nginx-proxy
        EOF